import { describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { createSeedState, YUHAN_ID } from "@/data/seed";
import { documentLanguageLabel, documentTypeLabel, handleDocumentDrop, nextDocumentVersion, titleFromFileName, validateDocumentFile } from "./document-metadata";
import { migrateState, serialiseState } from "./storage";
import type { CareerDocumentRecord } from "@/types/domain";

const manager = readFileSync(resolve("src/components/documents/document-manager.tsx"), "utf8");
const route = readFileSync(resolve("src/app/api/documents/route.ts"), "utf8");
const api = readFileSync(resolve("src/lib/document-api.ts"), "utf8");

describe("resume library UX", () => {
  it("keeps the native file input visually hidden behind a custom drop zone", () => { expect(manager).toMatch(/className="pointer-events-none absolute h-px w-px overflow-hidden opacity-0"\s+type="file"/); expect(manager).toContain('role="button"'); expect(manager).toContain("onDrop={drop}"); expect(manager).not.toContain("Choose file / No file chosen"); });
  it("prevents browser navigation for drag over and drop", () => { expect(manager).toContain('window.addEventListener("dragover", protect'); expect(manager).toContain('window.addEventListener("drop", protect'); expect(manager).toContain("event.preventDefault(); event.stopPropagation()"); });
  it("drop prevents defaults and sends the first file to the shared selection handler", () => { const file = { name: "resume.pdf" } as File; const preventDefault = vi.fn(); const stopPropagation = vi.fn(); const selected = vi.fn(); handleDocumentDrop({ preventDefault, stopPropagation, dataTransfer: { files: [file] } }, selected); expect(preventDefault).toHaveBeenCalledOnce(); expect(stopPropagation).toHaveBeenCalledOnce(); expect(selected).toHaveBeenCalledWith(file); });
  it("click selection and drop share handleSelectedFile", () => { expect(manager).toContain("handleDocumentDrop(event, handleSelectedFile)"); expect(manager).toContain("onChange={(event) => handleSelectedFile(event.target.files?.[0] ?? null)}"); });
  it("accepts PDF and DOCX", () => { expect(validateDocumentFile({ name: "resume.pdf", size: 100, type: "application/pdf" })).toBeNull(); expect(validateDocumentFile({ name: "resume.docx", size: 100, type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" })).toBeNull(); });
  it("rejects unsupported, mismatched and oversized files", () => { expect(validateDocumentFile({ name: "resume.txt", size: 100, type: "text/plain" })).toBe("type"); expect(validateDocumentFile({ name: "resume.pdf", size: 100, type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" })).toBe("type"); expect(validateDocumentFile({ name: "resume.pdf", size: 10 * 1024 * 1024 + 1, type: "application/pdf" })).toBe("size"); });
  it("generates readable titles without overwriting metadata logic", () => { expect(titleFromFileName("Jasmine_Yuan_Backend_Resume_v3.pdf")).toBe("Jasmine Yuan Backend Resume"); });
  it("increments versions within the same family", () => { const documents = [{ documentFamily: "English technical résumé", documentType: "English technical résumé", version: "v2", versionNumber: 2 }] as CareerDocumentRecord[]; expect(nextDocumentVersion(documents, "English technical résumé")).toBe(3); expect(nextDocumentVersion(documents, "Chinese product résumé")).toBe(1); });
  it("localises résumé types and languages", () => { expect(documentTypeLabel("Chinese technical résumé", "zh-CN")).toBe("中文技术简历"); expect(documentTypeLabel("Chinese technical résumé", "en")).toBe("Chinese technical résumé"); expect(documentLanguageLabel("Bilingual", "zh-CN")).toBe("中英双语"); expect(documentLanguageLabel("English", "en")).toBe("English"); });
  it("saves market and direction arrays and streams real upload states", () => { expect(manager).toContain('markets: JSON.stringify(draft.markets)'); expect(manager).toContain('directions: JSON.stringify(draft.directions)'); expect(route).toContain('send({ stage: "uploading" })'); expect(route).toContain('send({ stage: "parsing" })'); expect(route).toContain('send({ stage: "extracting" })'); expect(route).toContain('parsedStatus = "error"'); });
  it("keeps submit disabled until a real file and title are selected", () => { expect(manager).toContain("(!file || !draft.title.trim())"); });
  it("sends the real file as multipart FormData", () => { expect(api).toContain('const form = new FormData(); form.set("file", file)'); expect(api).toContain('body: form'); });
  it("persists successful uploads in the library and reloads them from the database", () => { expect(manager).toContain("upsertDocument(document)"); expect(manager).toContain("listCareerDocuments(activeWorkspace.profile.id)"); expect(route).toContain('from("career_documents").select("*")'); });
  it("does not insert a failed upload and removes its Storage object", () => { expect(route).toContain('if (error) { await auth.client.storage.from("career-documents").remove([storagePath])'); expect(route).toContain('catch (error) { await auth.client.storage.from("career-documents").remove([storagePath])'); });
  it("preserves old document records and cloud JSON serialization", () => { const state = createSeedState(); const legacy = { id: "legacy", profileId: YUHAN_ID, documentType: "English résumé", name: "Legacy", version: "v1", updatedAt: "2026-08-14", notes: "", status: "Missing" } satisfies CareerDocumentRecord; state.profiles[YUHAN_ID].documents = [legacy]; const migrated = migrateState(JSON.parse(serialiseState(state))); expect(migrated?.profiles[YUHAN_ID].documents[0]).toMatchObject({ name: "Legacy", markets: [], directions: [], versionNumber: 1, parsedStatus: "pending" }); expect(JSON.parse(serialiseState(migrated!)).profiles[YUHAN_ID].documents[0].name).toBe("Legacy"); });
  it("enforces one primary version and exposes responsive/mobile-safe controls", () => { const migration = readFileSync(resolve("supabase/migrations/20260814050248_documents_resume_library_metadata.sql"), "utf8"); expect(migration).toContain("career_documents_one_primary_per_family"); expect(manager).toContain("sm:grid-cols-2"); expect(manager).toContain("w-full sm:w-auto"); });
});
